// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type APIHit struct {
	UUID       string `json:"uuid"`
	CustomerID int    `json:"customerId"`
	ServiceID  int    `json:"serviceId"`
}

type Invoice struct {
	UUID       string    `json:"uuid"`
	CustomerID int       `json:"customerId"`
	Hits       []*APIHit `json:"hits"`
}
